[package]
name = "eqeval"
version = "0.1.0"
edition = "2021"
description = "An equation parser using the finum crate"
license = "MIT"

[dependencies]
rust_decimal = { version = "1.38.0", features = ["macros", "maths", "rand"] }
finum = "0.8.0"
